---
- name: Network Getting Started First Playbook Extended
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

  - name: Get config for ios devices
    ios_facts:
      gather_subnet: all

  - name: Display the config
      debug:
      msg: "The hostname is {{ ansible_net_hostname}} and the OS is {{ ansible_net_version }}"
#      msg: msg: “{{ hostvrs[inventory_hostname]}}”

  - name: change Hostname
    ios_config:
    backup: yes
    lines:
    - hostname Ansible_Configured

  - name: Get changed config for IOS devices
      ios_facts:
      gather_subnet: all

    - name: Display the config
      debug:
      msg: "The hostname is {{ ansible_net_hostname}} and the OS is {{ ansible_net_version }}"