---
all:
  children:
    VRF:
      children:
        Site1:
          hosts:
            R3:
              ansible_host: 10.0.0.1
            R5:
              ansible_host: 20.1.1.1
        Site2:
          hosts:
            R4:
              ansible_host: 10.1.1.1
            R6:
              ansible_host: 20.1.1.1
    PE:
      hosts:
        R1:
          ansible_host: 12.1.1.1
        R2:
          ansible_host: 23.1.1.2
        P:
          ansible_host: 12.1.1.2
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: anbible
    ansible_password: ansible