---
version: 1
build_arg_defaults:
  #EE_BASE_IMAGE: quay.io/ansible/awx-ee:latest
  #EE_BUILDER_IMAGE: quay.io/ansible/ansible-builder:latest
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
  ansible_config: 'ansible.cfg'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
# additional_build_steps:
#  prepend: |
#    RUN dnf upgrade -y
#    RUN pip3 install --upgrade pip setuptools
